export const siteConfig = {
  name: "Ashik",
  role: "MERN stack developer",
  bio: "I build web applications end to end, from React and Next.js interfaces to Node.js, real-time APIs and cloud deployments.",
  about:
    "I'm a MERN stack developer based in Kannur, Kerala, currently working at Dignizant Technologies. I work mostly on the front end, building interfaces with React, Next.js and TypeScript, and also handle the back end with Node.js and databases when needed. I started self-taught with the MERN stack and have shipped real products since.",
  skills: [
    "TypeScript",
    "JavaScript",
    "React",
    "Next.js",
    "Vite",
    "Redux",
    "Tailwind CSS",
    "Node.js",
    "Express.js",
    "Socket.IO",
    "REST APIs",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Prisma",
    "Supabase",
    "Redis",
    "SQLite",
    "IndexedDB",
    "Docker",
    "AWS EC2",
    "AWS S3",
    "Nginx",
    "Git",
    "n8n",
    "Zapier",
  ],
  experience: [
    {
      role: "MERN Stack Developer",
      company: "Dignizant Technologies",
      companyUrl: "https://dignizant.com/",
      location: "Surat, Gujarat",
      period: "2024 — Present",
      highlights: [
        "Build and maintain a multi-module SaaS workspace platform with spaces, channels, boards, threads and activity feeds, using React, TypeScript, Vite and Tailwind CSS.",
        "Ship real-time collaboration over Socket.IO and REST APIs, plus AI document workflows covering uploads, streaming responses and in-app viewing.",
        "Work across the stack on a team messaging platform, covering auth UI, file drive, contacts and chat end to end, with an offline-capable client layer using IndexedDB and SQLite.",
        "Own deployment and infrastructure for a client product on AWS EC2 and S3 with Docker, Nginx and SSL, backed by Node.js, Express and MongoDB, PostgreSQL and Prisma.",
        "Build third-party integrations syncing CRM, accounting and estimation data via OAuth, webhooks, n8n and Zapier, alongside FHIR interoperability and Stellar (SEP-31) payments.",
      ],
    },
  ],
  education: [
    {
      qualification: "MERN Stack Development",
      school: "Brototype",
      location: "Kozhikode, Kerala",
      period: "2023 — 2024",
      note: "Intensive mentored program covering front-end, back-end and full-stack development, where I built and deployed multiple MERN projects and grew from self-taught fundamentals to shipping complete applications.",
    },
    {
      qualification: "12th Standard · Junior Software Developer",
      school: "Vocational Higher Secondary, Chirakkara",
      location: "Thalassery, Kannur",
      period: "2020 — 2022",
      note: "Vocational track that introduced me to software development and set me on the path to becoming a MERN stack developer.",
    },
  ],
  projects: [
    {
      name: "Smart AI Test Suite (SAT)",
      description:
        "A unified CLI that uses AI agents to generate, run and auto-fix unit tests, analyzing code structure, dependencies and edge cases to produce ready-to-run tests in minutes.",
      tech: ["TypeScript", "Node.js", "Groq", "Llama 3.3", "Jest"],
      repo: "",
      live: "https://www.npmjs.com/package/smart-ai-terminal",
      terminal: true,
    },
    {
      name: "AshikNow",
      description:
        "A live personal stats hub. One terminal-styled page pulling live data from every platform I'm on: code, chess, typing, music, films and more, with journey pages and compare mode.",
      tech: ["TypeScript", "Next.js", "React", "Vercel"],
      repo: "https://github.com/Ashik234/AshikNow",
      live: "https://ashiknow.vercel.app",
    },
    {
      name: "Pause-ture",
      description:
        "A Windows break-reminder app that actually stops you, with fullscreen countdown-gated popups for eye, posture, water and walk breaks, idle detection and a ~4 MB Tauri installer.",
      tech: ["Rust", "Tauri", "TypeScript"],
      repo: "https://github.com/Ashik234/Pause-ture",
      live: "",
    },
    {
      name: "Matchday",
      description:
        "A football World Cup companion app with fixtures, teams and match data in a fast, modern interface.",
      tech: ["TypeScript", "Next.js", "React"],
      repo: "https://github.com/Ashik234/Matchday",
      live: "https://matchday-worldcup.vercel.app",
    },
  ],
  awards: [
    {
      title: "2nd Prize — Internal AI Hackathon",
      org: "Dignizant Technologies",
      date: "Jan 2026",
      note: "Won second prize as a team for building Smart AI Test Suite, an AI-powered automated unit-test generator.",
      image: "/awards/ai-hackathon.jpg",
      link: "",
    },
    {
      title: "Pioneer of Learning",
      org: "Dignizant Technologies",
      date: "Oct 2025",
      note: "Recognized during the company's 15th anniversary for continuous learning and contributing to a collaborative learning culture.",
      image: "/awards/pioneer-of-learning.jpg",
      link: "https://www.linkedin.com/posts/ashiik_continuouslearning-gratitude-dignizanttechnologies-activity-7382651863285915648-0df4",
    },
    {
      title: "Employee of the Quarter",
      org: "Dignizant Technologies",
      date: "Q1 2025 (Jan – Mar)",
      note: "Awarded for consistent contributions, teamwork and growth within the team.",
      image: "/awards/employee-of-the-quarter.jpg",
      link: "https://www.linkedin.com/posts/ashiik_feeling-truly-grateful-and-excited-to-be-activity-7326222893812514817-nZrT",
    },
  ],
  now: [
    "Learning Python",
    "Building Game Zone",
  ],
  available: true,
  availabilityText: "Available for work",
  resumePath: "/resume.pdf",
  photoPath: "/profile.jpg",
  socials: {
    github: "https://github.com/Ashik234",
    linkedin: "https://www.linkedin.com/in/ashiik",
    email: "ashikk.dev@gmail.com",
  },
  nav: [
    { label: "Ashik", href: "/" },
    { label: "About", href: "#about" },
    { label: "Projects", href: "#projects" },
    { label: "Connect", href: "#connect" },
  ],
} as const;

export type SiteConfig = typeof siteConfig;
